export enum ActionType {
  MOVE_CELL = 'move_cell',
  DELETE_CELL = 'delete_cell',
  INSERT_CELL_AFTER = 'insert_cell_after',
  UPDATE_CELL = 'update_cell',
  UPDATE_CELL_ORDER = 'update_cell_order',
  BUNDLE_IT = 'bundle_it',
  BUNDLE_CREATING = 'bundle_creating',
  BUNDLE_CREATED = 'bundle_created',
  ADD_DEPENDENCY = 'ADD_DEPENDENCY',
  REMOVE_DEPENDENCY = 'REMOVE_DEPENDENCY',
  UPDATE_DEPENDENCIES = 'UPDATE_DEPENDENCIES',
  ADD_NOTE = 'add_note',
  REMOVE_NOTE = 'remove_note',
}
